-- Schema para PokerFull

-- Tabla de jugadores (players)
CREATE TABLE public.players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    balance NUMERIC(10, 2) DEFAULT 0.00,
    current_stack NUMERIC(10, 2) DEFAULT 0.00,
    position INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Realtime para players
alter publication supabase_realtime add table public.players;

-- Insertar datos de prueba
INSERT INTO public.players (name, phone, balance, current_stack, position) VALUES
('Juan Perez', '+51999999991', 500, 500, 1),
('Maria Gomez', '+51999999992', 250, 250, 3),
('Carlos Diaz', '+51999999993', 1000, 1000, 5),
('Ana Rojas', '+51999999994', 150, 150, 8);

-- Tabla de transacciones (buy-ins / cash-outs)
CREATE TABLE public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT REFERENCES public.players(id),
    amount NUMERIC(10, 2) NOT NULL,
    type TEXT NOT NULL, -- 'buy-in' o 'cash-out'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Realtime para transactions
alter publication supabase_realtime add table public.transactions;

-- Configurar Storage (Crear un bucket llamado 'card-photos')
-- Esto debe hacerse manualmente desde la interfaz gráfica de Supabase
-- o usando el siguiente SQL si se tienen permisos sobre la bd de storage:
-- INSERT INTO storage.buckets (id, name, public) VALUES ('card-photos', 'card-photos', true);
